version: '3.8'
services:
  # PHP Service
  php:
    build:
      context: .
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT:-3306} # Default port for MySQL is 3306
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "${PORT:-8080}:80" # Use port 8080 or fallback to the environment variable
    depends_on:
      - database
      - redis
    entrypoint: ["/var/www/docker/entrypoint.sh"]

  # Database Service
  database:
    image: mysql:8.0
    container_name: database
    ports:
      - "${DB_PORT:-3306}:3306" # Default to 3306 or environment variable
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  # Redis Service
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6379:6379

volumes:
  db-data:
